import Head from "next/head";
import React from "react";
import Archive from "src/components/Archive";
import Layout from "src/components/layout";
import { PostProps } from "src/types/posts";

type Props = {
  posts: PostProps[];
};

const Pagination = ({ posts }: Props) => {
  return (
    <>
      <Layout>
        <Head>
          <title>Canalapps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Archive posts={posts} />
      </Layout>
    </>
  );
};

export default Pagination;

export async function getStaticProps({ params }: any) {
  const res = await fetch(
    `https://www.canalapps.com/wp-json/wp/v2/posts?page=${params.page}`
  );
  const posts = await res.json();
  return { props: { posts } };
}

export async function getStaticPaths() {
  const resPosts = await fetch(`https://www.canalapps.com/wp-json/wp/v2/posts`);
  const totalPages: number = +(resPosts.headers.get("x-wp-totalpages") || 1);
  const paths = [];

  for (let page = 2; page <= totalPages; page++) {
    paths.push({ params: { page: page.toString() } });
  }
  return {
    paths,
    fallback: false,
  };
}
