import Head from "next/head";
import React from "react";
import Layout from "src/layout";
import List from "src/components/List";
import { PostProps } from "src/types/posts";

type Props = { posts: PostProps[]; totalPages: number };

const Home = ({ posts }: Props) => {
  return (
    <Layout>
      <Head>
        <title>Canalapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List posts={posts} />
    </Layout>
  );
};

export default Home;
