import Head from "next/head";
import Layout from "src/layout";
import List from "src/components/List";
import { MenuProps } from "src/types/menus";
import { PostProps } from "src/types/posts";

type Props = {
  posts: PostProps[];
  menuHeader: MenuProps;
  menuFooter: MenuProps;
};

const Paginated = ({ posts, menuFooter, menuHeader }: Props) => {
  return (
    <Layout menuFooter={menuFooter} menuHeader={menuHeader}>
      <Head>
        <title>Canalapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List posts={posts} />
    </Layout>
  );
};

export default Paginated;
