import Layout from "src/components/layout";
import Head from "next/head";
import { PostProps } from "src/types/posts";
import Archive from "src/components/Archive";

type Props = {
  posts: PostProps[];
  totalPages: number;
};

const Home = ({ posts, totalPages }: Props) => {
  return (
    <>
      <Layout>
        <Head>
          <title>Canalapps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Archive posts={posts} />
      </Layout>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const resPosts = await fetch(
    `https://www.canalapps.com/wp-json/wp/v2/posts?page=1`
  );
  const posts = await resPosts.json();

  const totalPages = resPosts.headers.get("x-wp-totalpages");
  return { props: { posts, totalPages }, revalidate: 600 };
}
