import { BoxProps } from "@mui/material";
import Head from "next/head";
import React, { ReactChild, ReactNode } from "react";
import { MenuProps } from "src/types/menus";
import Footer from "./Footer";
import Header from "./Header";

type Props = {
  children: ReactNode;
  menuHeader: MenuProps;
  menuFooter: MenuProps;
};

const Layout = ({ children, menuHeader, menuFooter }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header menuHeader={menuHeader} />
      <main style={{ overflow: "hidden" }}>{children}</main>
      <Footer menuFooter={menuFooter} />
    </>
  );
};

export default Layout;
